CREATE TABLE IF NOT EXISTS weather_current (
  city_code VARCHAR(20) NOT NULL,
  city_name VARCHAR(50) NOT NULL,
  nx SMALLINT UNSIGNED NOT NULL,
  ny SMALLINT UNSIGNED NOT NULL,
  base_date CHAR(8) NOT NULL,
  base_time CHAR(4) NOT NULL,
  observed_at DATETIME NOT NULL,
  temperature_c DECIMAL(4,1) NULL,
  humidity_percent TINYINT UNSIGNED NULL,
  precipitation_type TINYINT UNSIGNED NULL,
  precipitation_type_name VARCHAR(20) NOT NULL DEFAULT '없음',
  precipitation_1h VARCHAR(30) NULL,
  precipitation_1h_mm DECIMAL(6,1) NULL,
  wind_speed_ms DECIMAL(5,1) NULL,
  wind_direction_deg SMALLINT UNSIGNED NULL,
  raw_payload LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (city_code),
  KEY idx_observed_at (observed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS weather_forecast (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  city_code VARCHAR(20) NOT NULL,
  city_name VARCHAR(50) NOT NULL,
  nx SMALLINT UNSIGNED NOT NULL,
  ny SMALLINT UNSIGNED NOT NULL,
  base_date CHAR(8) NOT NULL,
  base_time CHAR(4) NOT NULL,
  forecast_date CHAR(8) NOT NULL,
  forecast_time CHAR(4) NOT NULL,
  forecast_at DATETIME NOT NULL,
  temperature_c DECIMAL(4,1) NULL,
  temp_min_c DECIMAL(4,1) NULL,
  temp_max_c DECIMAL(4,1) NULL,
  sky_code TINYINT UNSIGNED NULL,
  sky_name VARCHAR(20) NULL,
  precipitation_type TINYINT UNSIGNED NULL,
  precipitation_type_name VARCHAR(20) NOT NULL DEFAULT '없음',
  precipitation_probability_percent TINYINT UNSIGNED NULL,
  precipitation_amount VARCHAR(30) NULL,
  humidity_percent TINYINT UNSIGNED NULL,
  wind_speed_ms DECIMAL(5,1) NULL,
  raw_payload LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_city_forecast_time (city_code, forecast_date, forecast_time),
  KEY idx_forecast_at (forecast_at),
  KEY idx_city_forecast_at (city_code, forecast_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
